version: "3"

services:
  app:
    build: .
    user: "1000:1000"
    container_name: table_actions_dev
    stdin_open: true
    command:
      - "/bin/sh"
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - ".:/app"

volumes:
  node_modules:

