version: "3"

services:
  app:
    build:
      context: ./
      dockerfile: ./docker/dev/Dockerfile
    user: "1000:1000"
    container_name: ta_dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
