services:
  app:
    command:
      - /bin/sh
      - -c
      - |
        yarn run build 2>/dev/null
        yarn run lite-server &
        yarn run test
    volumes:
      - "./tests:/app/tests"
      - "./src:/app/src"
      - "./demo:/app/demo"
